name: NetherPortals
version: 1.1
api-version: 1.13
author: Rene Hampoelz
website: hampoelz.net

main: net.hampoelz.NetherPortals.main.Main

softdepend: [AsyncWorldManager]

commands:
  netherportals:
    usage: /NetherPortals reload
    description: Reload the config file
    aliases: [np]
    
permissions:
  NetherPortals.*:
    children:
      NetherPortals.reload: true
